all:
#	g++ execTest.cpp -o execTest
#	g++ explicitTest.cpp -o explicitTest
#	g++ hello.cpp -o hello -std=c++11
#	g++ staticMemberTest.cpp -o staticMemberTest
#	gcc crashTest.c -o crashTest
#	gcc string.c -o string
#	g++ macroFunction.cpp -o macroFunction -std=c++11
	#g++ iterator.cpp -o iterator -std=c++11
	#g++ delete.cpp -o delete -std=c++11
	g++ transform.cpp -o transform -std=c++11

