all:
	#g++ stackArray.cpp main.cpp -o main -std=c++11
	#g++ hanoi.cpp -o hanoi -std=c++11
	#g++ twoStackQueue.cpp -o twoStackQueue -std=c++11
	#g++ sort.cpp -o sort -std=c++11
	g++ twoQueueStack.cpp -o twoQueueStack -std=c++11
