all:
#	g++ test.cpp sort.cpp -o test -std=c++11
#	g++ 9-1.cpp sort.cpp -o 9-1 -std=c++11
#	g++ 9-2.cpp sort.cpp -o 9-2 -std=c++11
#	g++ 9-3.cpp sort.cpp -o 9-3 -std=c++11
#	g++ 9-5.cpp sort.cpp -o 9-5 -std=c++11
#	g++ 9-6.cpp sort.cpp -o 9-6 -std=c++11
	g++ 9-7.cpp sort.cpp -o 9-7 -std=c++11
#	g++ 9-6.cpp sort.cpp -o 9-6 -std=c++11
#	g++ 9-4.cpp sort.cpp -o 9-4 -std=c++11
#	g++ dataGenerator.cpp -o dataGenerator -std=c++11
#	g++ dataGenerator.cpp -o dataGenerator -std=c++11
