all:
#	g++ test.cpp binarySearchTree.cpp -o test
#	g++ 4-1.cpp binarySearchTree.cpp -o 4-1
#	g++ 4-3.cpp binarySearchTree.cpp -o 4-3
#	g++ 4-4.cpp binarySearchTree.cpp -o 4-4
#	g++ 4-5.cpp binarySearchTree.cpp -o 4-5
#	g++ 4-6.cpp binarySearchTree.cpp -o 4-6
#	g++ 4-7.cpp binarySearchTree.cpp -o 4-7
	g++ 4-8.cpp binarySearchTree.cpp -o 4-8
#	g++ 4-2.cpp -o 4-2

