all:
#	g++ test.cpp BitManipulation.cpp -o test
#	g++ 5-1.cpp BitManipulation.cpp -o 5-1
#	g++ 5-2.cpp BitManipulation.cpp -o 5-2
#	g++ 5-3.cpp BitManipulation.cpp -o 5-3
#	g++ 5-4.cpp BitManipulation.cpp -o 5-4
#	g++ 5-5.cpp BitManipulation.cpp -o 5-5
	g++ 5-6.cpp BitManipulation.cpp -o 5-6

